# Hand-written stub for the compiled _core extension. Keep in sync with
# src/flxscalers/bindings/.

import numpy as np
import numpy.typing as npt

class MinMaxScaler:
    def __init__(self, feature_range: tuple[float, float] = ...) -> None: ...
    def fit(self, X: npt.ArrayLike) -> MinMaxScaler: ...
    def transform(self, X: npt.ArrayLike) -> npt.NDArray[np.float64]: ...
    def fit_transform(self, X: npt.ArrayLike) -> npt.NDArray[np.float64]: ...
    def inverse_transform(self, X: npt.ArrayLike) -> npt.NDArray[np.float64]: ...
